"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.button import Button
globals()['Button'] = Button
from openapi_client.model.explanation_start_tracking import ExplanationStartTracking


class TestExplanationStartTracking(unittest.TestCase):
    """ExplanationStartTracking unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExplanationStartTracking(self):
        """Test ExplanationStartTracking"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExplanationStartTracking()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
