"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.authorized_clients import AuthorizedClients
from openapi_client.model.card import Card
from openapi_client.model.error_response import ErrorResponse
globals()['AuthorizedClients'] = AuthorizedClients
globals()['Card'] = Card
globals()['ErrorResponse'] = ErrorResponse
from openapi_client.model.get_shares_response import GetSharesResponse


class TestGetSharesResponse(unittest.TestCase):
    """GetSharesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSharesResponse(self):
        """Test GetSharesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSharesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
