"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.button import Button
from openapi_client.model.input_field import InputField
globals()['Button'] = Button
globals()['InputField'] = InputField
from openapi_client.model.card import Card


class TestCard(unittest.TestCase):
    """Card unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCard(self):
        """Test Card"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Card()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
