"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.tracking_reminder_notification_action import TrackingReminderNotificationAction
from openapi_client.model.tracking_reminder_notification_track_all_action import TrackingReminderNotificationTrackAllAction
from openapi_client.model.unit import Unit
globals()['Card'] = Card
globals()['TrackingReminderNotificationAction'] = TrackingReminderNotificationAction
globals()['TrackingReminderNotificationTrackAllAction'] = TrackingReminderNotificationTrackAllAction
globals()['Unit'] = Unit
from openapi_client.model.tracking_reminder_notification import TrackingReminderNotification


class TestTrackingReminderNotification(unittest.TestCase):
    """TrackingReminderNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackingReminderNotification(self):
        """Test TrackingReminderNotification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrackingReminderNotification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
