"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.button import Button
from openapi_client.model.card import Card
from openapi_client.model.connect_instructions import ConnectInstructions
globals()['Button'] = Button
globals()['Card'] = Card
globals()['ConnectInstructions'] = ConnectInstructions
from openapi_client.model.data_source import DataSource


class TestDataSource(unittest.TestCase):
    """DataSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataSource(self):
        """Test DataSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
