"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.correlation import Correlation
from openapi_client.model.error_response import ErrorResponse
from openapi_client.model.explanation import Explanation
globals()['Card'] = Card
globals()['Correlation'] = Correlation
globals()['ErrorResponse'] = ErrorResponse
globals()['Explanation'] = Explanation
from openapi_client.model.get_correlations_data_response import GetCorrelationsDataResponse


class TestGetCorrelationsDataResponse(unittest.TestCase):
    """GetCorrelationsDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCorrelationsDataResponse(self):
        """Test GetCorrelationsDataResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCorrelationsDataResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
