"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.conversion_step import ConversionStep
from openapi_client.model.unit_category import UnitCategory
globals()['ConversionStep'] = ConversionStep
globals()['UnitCategory'] = UnitCategory
from openapi_client.model.unit import Unit


class TestUnit(unittest.TestCase):
    """Unit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnit(self):
        """Test Unit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Unit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
