"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user_tag import UserTag


class TestUserTag(unittest.TestCase):
    """UserTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserTag(self):
        """Test UserTag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserTag()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
