"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.correlation import Correlation
from openapi_client.model.participant_instruction import ParticipantInstruction
from openapi_client.model.study_charts import StudyCharts
from openapi_client.model.study_html import StudyHtml
from openapi_client.model.study_images import StudyImages
from openapi_client.model.study_links import StudyLinks
from openapi_client.model.study_sharing import StudySharing
from openapi_client.model.study_text import StudyText
from openapi_client.model.study_votes import StudyVotes
from openapi_client.model.variable import Variable
globals()['Card'] = Card
globals()['Correlation'] = Correlation
globals()['ParticipantInstruction'] = ParticipantInstruction
globals()['StudyCharts'] = StudyCharts
globals()['StudyHtml'] = StudyHtml
globals()['StudyImages'] = StudyImages
globals()['StudyLinks'] = StudyLinks
globals()['StudySharing'] = StudySharing
globals()['StudyText'] = StudyText
globals()['StudyVotes'] = StudyVotes
globals()['Variable'] = Variable
from openapi_client.model.study import Study


class TestStudy(unittest.TestCase):
    """Study unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudy(self):
        """Test Study"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Study()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
