"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.data_source import DataSource
from openapi_client.model.error_response import ErrorResponse
globals()['Card'] = Card
globals()['DataSource'] = DataSource
globals()['ErrorResponse'] = ErrorResponse
from openapi_client.model.get_connectors_response import GetConnectorsResponse


class TestGetConnectorsResponse(unittest.TestCase):
    """GetConnectorsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetConnectorsResponse(self):
        """Test GetConnectorsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetConnectorsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
