"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.tracking_reminder_notification_track_all_action import TrackingReminderNotificationTrackAllAction


class TestTrackingReminderNotificationTrackAllAction(unittest.TestCase):
    """TrackingReminderNotificationTrackAllAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackingReminderNotificationTrackAllAction(self):
        """Test TrackingReminderNotificationTrackAllAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrackingReminderNotificationTrackAllAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
