"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.error_response import ErrorResponse
from openapi_client.model.study import Study
from openapi_client.model.tracking_reminder import TrackingReminder
from openapi_client.model.tracking_reminder_notification import TrackingReminderNotification
globals()['Card'] = Card
globals()['ErrorResponse'] = ErrorResponse
globals()['Study'] = Study
globals()['TrackingReminder'] = TrackingReminder
globals()['TrackingReminderNotification'] = TrackingReminderNotification
from openapi_client.model.study_join_response import StudyJoinResponse


class TestStudyJoinResponse(unittest.TestCase):
    """StudyJoinResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudyJoinResponse(self):
        """Test StudyJoinResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudyJoinResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
