"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.data_source import DataSource
from openapi_client.model.tracking_reminder_notification_action import TrackingReminderNotificationAction
from openapi_client.model.unit import Unit
from openapi_client.model.variable_category import VariableCategory
from openapi_client.model.variable_charts import VariableCharts
globals()['Card'] = Card
globals()['DataSource'] = DataSource
globals()['TrackingReminderNotificationAction'] = TrackingReminderNotificationAction
globals()['Unit'] = Unit
globals()['VariableCategory'] = VariableCategory
globals()['VariableCharts'] = VariableCharts
from openapi_client.model.variable import Variable


class TestVariable(unittest.TestCase):
    """Variable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVariable(self):
        """Test Variable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Variable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
