"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.app_settings import AppSettings
from openapi_client.model.card import Card
from openapi_client.model.error_response import ErrorResponse
globals()['AppSettings'] = AppSettings
globals()['Card'] = Card
globals()['ErrorResponse'] = ErrorResponse
from openapi_client.model.app_settings_response import AppSettingsResponse


class TestAppSettingsResponse(unittest.TestCase):
    """AppSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppSettingsResponse(self):
        """Test AppSettingsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AppSettingsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
