"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.device_token import DeviceToken


class TestDeviceToken(unittest.TestCase):
    """DeviceToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceToken(self):
        """Test DeviceToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
