"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.error_response import ErrorResponse
from openapi_client.model.post_tracking_reminders_data_response import PostTrackingRemindersDataResponse
globals()['Card'] = Card
globals()['ErrorResponse'] = ErrorResponse
globals()['PostTrackingRemindersDataResponse'] = PostTrackingRemindersDataResponse
from openapi_client.model.post_tracking_reminders_response import PostTrackingRemindersResponse


class TestPostTrackingRemindersResponse(unittest.TestCase):
    """PostTrackingRemindersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostTrackingRemindersResponse(self):
        """Test PostTrackingRemindersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostTrackingRemindersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
