"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.explanation_start_tracking import ExplanationStartTracking
from openapi_client.model.image import Image
globals()['ExplanationStartTracking'] = ExplanationStartTracking
globals()['Image'] = Image
from openapi_client.model.explanation import Explanation


class TestExplanation(unittest.TestCase):
    """Explanation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExplanation(self):
        """Test Explanation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Explanation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
