"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.measurement_update import MeasurementUpdate


class TestMeasurementUpdate(unittest.TestCase):
    """MeasurementUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasurementUpdate(self):
        """Test MeasurementUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MeasurementUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
