"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.data_source import DataSource
from openapi_client.model.study_html import StudyHtml
from openapi_client.model.study_images import StudyImages
from openapi_client.model.study_links import StudyLinks
from openapi_client.model.study_text import StudyText
globals()['DataSource'] = DataSource
globals()['StudyHtml'] = StudyHtml
globals()['StudyImages'] = StudyImages
globals()['StudyLinks'] = StudyLinks
globals()['StudyText'] = StudyText
from openapi_client.model.correlation import Correlation


class TestCorrelation(unittest.TestCase):
    """Correlation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCorrelation(self):
        """Test Correlation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Correlation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
