"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.user import User
globals()['User'] = User
from openapi_client.model.app_settings import AppSettings


class TestAppSettings(unittest.TestCase):
    """AppSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppSettings(self):
        """Test AppSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AppSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
