"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.error_response import ErrorResponse
from openapi_client.model.tracking_reminder_notification import TrackingReminderNotification
globals()['Card'] = Card
globals()['ErrorResponse'] = ErrorResponse
globals()['TrackingReminderNotification'] = TrackingReminderNotification
from openapi_client.model.get_tracking_reminder_notifications_response import GetTrackingReminderNotificationsResponse


class TestGetTrackingReminderNotificationsResponse(unittest.TestCase):
    """GetTrackingReminderNotificationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTrackingReminderNotificationsResponse(self):
        """Test GetTrackingReminderNotificationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTrackingReminderNotificationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
