"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.card import Card
from openapi_client.model.tracking_reminder_notification_action import TrackingReminderNotificationAction
from openapi_client.model.unit import Unit
globals()['Card'] = Card
globals()['TrackingReminderNotificationAction'] = TrackingReminderNotificationAction
globals()['Unit'] = Unit
from openapi_client.model.tracking_reminder import TrackingReminder


class TestTrackingReminder(unittest.TestCase):
    """TrackingReminder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrackingReminder(self):
        """Test TrackingReminder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrackingReminder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
