"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.study_images import StudyImages


class TestStudyImages(unittest.TestCase):
    """StudyImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudyImages(self):
        """Test StudyImages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudyImages()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
