"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.measurement_item import MeasurementItem


class TestMeasurementItem(unittest.TestCase):
    """MeasurementItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasurementItem(self):
        """Test MeasurementItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MeasurementItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
