"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class Pair(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'cause_measurement': (float,),  # noqa: E501
            'cause_measurement_value': (float,),  # noqa: E501
            'cause_variable_unit_abbreviated_name': (str,),  # noqa: E501
            'effect_measurement': (float,),  # noqa: E501
            'effect_measurement_value': (float,),  # noqa: E501
            'effect_variable_unit_abbreviated_name': (str,),  # noqa: E501
            'timestamp': (int,),  # noqa: E501
            'event_at': (str,),  # noqa: E501
            'event_at_unix_time': (int,),  # noqa: E501
            'start_time_string': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'cause_measurement': 'causeMeasurement',  # noqa: E501
        'cause_measurement_value': 'causeMeasurementValue',  # noqa: E501
        'cause_variable_unit_abbreviated_name': 'causeVariableUnitAbbreviatedName',  # noqa: E501
        'effect_measurement': 'effectMeasurement',  # noqa: E501
        'effect_measurement_value': 'effectMeasurementValue',  # noqa: E501
        'effect_variable_unit_abbreviated_name': 'effectVariableUnitAbbreviatedName',  # noqa: E501
        'timestamp': 'timestamp',  # noqa: E501
        'event_at': 'eventAt',  # noqa: E501
        'event_at_unix_time': 'eventAtUnixTime',  # noqa: E501
        'start_time_string': 'startTimeString',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, cause_measurement, cause_measurement_value, cause_variable_unit_abbreviated_name, effect_measurement, effect_measurement_value, effect_variable_unit_abbreviated_name, timestamp, *args, **kwargs):  # noqa: E501
        """Pair - a model defined in OpenAPI

        Args:
            cause_measurement (float): Ex: 101341.66666667
            cause_measurement_value (float): Ex: 101341.66666667
            cause_variable_unit_abbreviated_name (str): Ex: mg
            effect_measurement (float): Ex: 7.98
            effect_measurement_value (float): Ex: 7.98
            effect_variable_unit_abbreviated_name (str): Ex: %
            timestamp (int): Ex: 1464937200

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            event_at (str): Ex: 2015-08-06 15:49:02 UTC ISO 8601 YYYY-MM-DDThh:mm:ss. [optional]  # noqa: E501
            event_at_unix_time (int): Ex: 1438876142. [optional]  # noqa: E501
            start_time_string (str): Ex: 2015-08-06 15:49:02 UTC ISO 8601 YYYY-MM-DDThh:mm:ss. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.cause_measurement = cause_measurement
        self.cause_measurement_value = cause_measurement_value
        self.cause_variable_unit_abbreviated_name = cause_variable_unit_abbreviated_name
        self.effect_measurement = effect_measurement
        self.effect_measurement_value = effect_measurement_value
        self.effect_variable_unit_abbreviated_name = effect_variable_unit_abbreviated_name
        self.timestamp = timestamp
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
