"""
    CureDAO Unified Health API

    A platform for participant-centered research and personal data exploration  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

import nulltype  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class VariableCategory(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('variable_category_name',): {
            'ACTIVITY': "Activity",
            'BOOKS': "Books",
            'CAUSES_OF_ILLNESS': "Causes of Illness",
            'COGNITIVE_PERFORMANCE': "Cognitive Performance",
            'CONDITIONS': "Conditions",
            'EMOTIONS': "Emotions",
            'ENVIRONMENT': "Environment",
            'FOODS': "Foods",
            'GOALS': "Goals",
            'LOCATIONS': "Locations",
            'MISCELLANEOUS': "Miscellaneous",
            'MOVIES_AND_TV': "Movies and TV",
            'MUSIC': "Music",
            'NUTRIENTS': "Nutrients",
            'PAYMENTS': "Payments",
            'PHYSICAL_ACTIVITIES': "Physical Activities",
            'PHYSIQUE': "Physique",
            'SLEEP': "Sleep",
            'SOCIAL_INTERACTIONS': "Social Interactions",
            'SOFTWARE': "Software",
            'SYMPTOMS': "Symptoms",
            'TREATMENTS': "Treatments",
            'VITAL_SIGNS': "Vital Signs",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'name': (str,),  # noqa: E501
            'app_type': (str,),  # noqa: E501
            'cause_only': (bool,),  # noqa: E501
            'combination_operation': (str,),  # noqa: E501
            'created_time': (str,),  # noqa: E501
            'unit_abbreviated_name': (str,),  # noqa: E501
            'unit_id': (int,),  # noqa: E501
            'duration_of_action': (int,),  # noqa: E501
            'filling_value': (int,),  # noqa: E501
            'help_text': (str,),  # noqa: E501
            'id': (int,),  # noqa: E501
            'image_url': (str,),  # noqa: E501
            'ion_icon': (str,),  # noqa: E501
            'manual_tracking': (bool,),  # noqa: E501
            'maximum_allowed_value': (str,),  # noqa: E501
            'measurement_synonym_singular_lowercase': (str,),  # noqa: E501
            'minimum_allowed_value': (str,),  # noqa: E501
            'more_info': (str,),  # noqa: E501
            'onset_delay': (int,),  # noqa: E501
            'outcome': (bool,),  # noqa: E501
            'png_path': (str,),  # noqa: E501
            'png_url': (str,),  # noqa: E501
            'public': (bool,),  # noqa: E501
            'svg_path': (str,),  # noqa: E501
            'svg_url': (str,),  # noqa: E501
            'updated': (int,),  # noqa: E501
            'updated_time': (str,),  # noqa: E501
            'variable_category_name': (str,),  # noqa: E501
            'variable_category_name_singular': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'name': 'name',  # noqa: E501
        'app_type': 'appType',  # noqa: E501
        'cause_only': 'causeOnly',  # noqa: E501
        'combination_operation': 'combinationOperation',  # noqa: E501
        'created_time': 'createdTime',  # noqa: E501
        'unit_abbreviated_name': 'unitAbbreviatedName',  # noqa: E501
        'unit_id': 'unitId',  # noqa: E501
        'duration_of_action': 'durationOfAction',  # noqa: E501
        'filling_value': 'fillingValue',  # noqa: E501
        'help_text': 'helpText',  # noqa: E501
        'id': 'id',  # noqa: E501
        'image_url': 'imageUrl',  # noqa: E501
        'ion_icon': 'ionIcon',  # noqa: E501
        'manual_tracking': 'manualTracking',  # noqa: E501
        'maximum_allowed_value': 'maximumAllowedValue',  # noqa: E501
        'measurement_synonym_singular_lowercase': 'measurementSynonymSingularLowercase',  # noqa: E501
        'minimum_allowed_value': 'minimumAllowedValue',  # noqa: E501
        'more_info': 'moreInfo',  # noqa: E501
        'onset_delay': 'onsetDelay',  # noqa: E501
        'outcome': 'outcome',  # noqa: E501
        'png_path': 'pngPath',  # noqa: E501
        'png_url': 'pngUrl',  # noqa: E501
        'public': 'public',  # noqa: E501
        'svg_path': 'svgPath',  # noqa: E501
        'svg_url': 'svgUrl',  # noqa: E501
        'updated': 'updated',  # noqa: E501
        'updated_time': 'updatedTime',  # noqa: E501
        'variable_category_name': 'variableCategoryName',  # noqa: E501
        'variable_category_name_singular': 'variableCategoryNameSingular',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, name, *args, **kwargs):  # noqa: E501
        """VariableCategory - a model defined in OpenAPI

        Args:
            name (str): Category name

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            app_type (str): Ex: mood. [optional]  # noqa: E501
            cause_only (bool): Ex: false. [optional]  # noqa: E501
            combination_operation (str): Ex: MEAN. [optional]  # noqa: E501
            created_time (str): UTC ISO 8601 YYYY-MM-DDThh:mm:ss. [optional]  # noqa: E501
            unit_abbreviated_name (str): Ex: /5. [optional]  # noqa: E501
            unit_id (int): Ex: 10. [optional]  # noqa: E501
            duration_of_action (int): User-Defined Variable Setting: The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.  Unit: Seconds. [optional]  # noqa: E501
            filling_value (int): Ex: -1. Unit: Variable category default unit.. [optional]  # noqa: E501
            help_text (str): Ex: What emotion do you want to rate?. [optional]  # noqa: E501
            id (int): Ex: 1. [optional]  # noqa: E501
            image_url (str): Ex: https://static.quantimo.do/img/variable_categories/theatre_mask-96.png. [optional]  # noqa: E501
            ion_icon (str): Ex: ion-happy-outline. [optional]  # noqa: E501
            manual_tracking (bool): Ex: true. [optional]  # noqa: E501
            maximum_allowed_value (str): Unit: Variable category default unit.. [optional]  # noqa: E501
            measurement_synonym_singular_lowercase (str): Ex: rating. [optional]  # noqa: E501
            minimum_allowed_value (str): Unit: Variable category default unit.. [optional]  # noqa: E501
            more_info (str): Ex: Do you have any emotions that fluctuate regularly?  If so, add them so I can try to determine which factors are influencing them.. [optional]  # noqa: E501
            onset_delay (int): Ex: 0. [optional]  # noqa: E501
            outcome (bool): Ex: true. [optional]  # noqa: E501
            png_path (str): Ex: img/variable_categories/emotions.png. [optional]  # noqa: E501
            png_url (str): Ex: https://app.curedao.org/img/variable_categories/emotions.png. [optional]  # noqa: E501
            public (bool): Ex: true. [optional]  # noqa: E501
            svg_path (str): Ex: img/variable_categories/emotions.svg. [optional]  # noqa: E501
            svg_url (str): Ex: https://app.curedao.org/img/variable_categories/emotions.svg. [optional]  # noqa: E501
            updated (int): Ex: 1. [optional]  # noqa: E501
            updated_time (str): UTC ISO 8601 YYYY-MM-DDThh:mm:ss. [optional]  # noqa: E501
            variable_category_name (str): Ex: Emotions, Treatments, Symptoms.... [optional]  # noqa: E501
            variable_category_name_singular (str): Ex: Emotion. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.name = name
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
